### PR TITLE
add Node Version Manager support

### PR DESCRIPTION
**Pull request by Grawl**
[`.nvmrc`](https://github.com/nvm-sh/nvm#nvmrc) file is for Node Version Manager

there is a [Feature Request](https://github.com/nvm-sh/nvm/issues/651) to use `engines.node` from `package.json` but for now only a separate file is supported

### CODE REVIEW

**Comment by ai** [comment]
To be honest, I am not a big fan of using non-standard dev files.

You can use `.nvmrc` by adding it to `.git/info/exclude`.

What are your reasons to give this file to everyone?

**Comment by Grawl** [comment]
Many people uses NVM to run required Node version for projects. Some requires 10, some requires 13.

**Comment by ai** [comment]
Hm. It will have more sense if we will use the same `nvm` in GitHub Actions (I do not like to add more configs, but I like to reduce code duplication).

You can replace `@actions/setup-node with https://github.com/dcodeIO/setup-node-nvm in GitHub Action configs.

**Comment by ai** [comment]
Closing because of lack of answer

**Pull request closed without merging**
