### PR TITLE
Add "examples" section

### PR DESCRIPTION
**Pull request by VladBrok**
Related to https://github.com/logux/docs/pull/98

### CODE REVIEW

**Comment by ai** [comment]
I created Recipes with the same purpose as your Example. Do you see a difference between them?

**Comment by VladBrok** [comment]
I thought that Recipes are meant to include step-by-step instructions for common cases (auth, deployment, etc.), but in Examples I included a repository with sample application (but if it's better to add an example to Recipes then I'll update the PR)

**Comment by ai** [comment]
The difference is too shady. Your example and pretty similar with step-by-step guide.

Let’s avoid creating menu section for the single element. Can you change that PR?

**Comment by VladBrok** [comment]
sure, I've updated the PR: https://github.com/logux/docs/pull/98

**Pull request closed without merging**
